apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: velero
  namespace: velero
spec:
  selector:
    matchLabels:
      component: velero
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s