apiVersion: v1
kind: Service
metadata:
  name: velero-metrics
  namespace: velero
  labels:
    component: velero
spec:
  selector:
    component: velero
  ports:
    - name: http-metrics
      port: 8085
      targetPort: 8085