apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opencost
  namespace: opencost
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: opencost
  namespaceSelector:
    matchNames:
      - opencost
  endpoints:
    - port: opencost
      path: /metrics
      interval: 30s
