{
 "title": "Next Gen K8s Management Dashboard",
 "description": "This Dashboard is used to visualise the metrics from the security reports of the Trivy Operator",
 "tags": [
  "trivy",
  "trivy operator",
  "security",
  "security scanning",
  "vulnerabilities",
  "exposed secrets",
  "misconfiguration"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Quick Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number and Type of Security Issues",
   "type": "stat",
   "description": "Total number by type of security issues identified in the cluster",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities)",
     "legendFormat": "Vulnerabilities"
    },
    {
     "expr": "sum(trivy_resource_configaudits)",
     "legendFormat": "Misconfiguration"
    },
    {
     "expr": "sum(trivy_image_exposedsecrets)",
     "legendFormat": "Exposed Secrets"
    },
    {
     "expr": "sum(trivy_clusterrole_clusterrbacassessments)",
     "legendFormat": "RBAC Assessment"
    }
   ]
  },
  { "title": "Vulnerabilities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Severity Breakdown of all Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Critical\"})",
     "legendFormat": "Critical"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"High\"})",
     "legendFormat": "High"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Medium\"})",
     "legendFormat": "Medium"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Low\"})",
     "legendFormat": "Low"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Unknown\"})",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "VulnerabilityReport CVEs (Across All Resources)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(vuln_critical_total)", "legendFormat": "Critical CVEs" },
    { "expr": "sum(vuln_high_total)", "legendFormat": "High CVEs" },
    { "expr": "sum(vuln_medium_total)", "legendFormat": "Medium CVEs" },
    { "expr": "sum(vuln_low_total)", "legendFormat": "Low CVEs" },
    { "expr": "sum(vuln_unknown_total)", "legendFormat": "Unknown CVEs" },
    { "expr": "sum(vuln_total_count)", "legendFormat": "Total CVEs" }
   ]
  },
  {
   "title": "ConfigAudit Report Summary",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(configaudit_critical_count)",
     "legendFormat": "Critical"
    },
    { "expr": "sum(configaudit_high_count)", "legendFormat": "High" },
    { "expr": "sum(configaudit_medium_count)", "legendFormat": "Medium" },
    { "expr": "sum(configaudit_low_count)", "legendFormat": "Low" }
   ]
  },
  {
   "title": "CVE Severity Summary (per Namespace)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    { "expr": "vuln_critical_total", "legendFormat": "Critical" },
    { "expr": "vuln_high_total", "legendFormat": "High" },
    { "expr": "vuln_medium_total", "legendFormat": "Medium" },
    { "expr": "vuln_low_total", "legendFormat": "Low" },
    { "expr": "vuln_unknown_total", "legendFormat": "Unknown" }
   ]
  },
  {
   "title": "Vulnerability by Image",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Critical\"}) by (image_repository,image_tag)"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"High\"}) by (image_repository,image_tag)"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Medium\"}) by (image_repository,image_tag)"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Low\"}) by (image_repository,image_tag)"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Unknown\"}) by (image_repository,image_tag)"
    }
   ]
  },
  {
   "title": "VulnerabilityReport CVEs (Per Workload)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 59 },
   "targets": [
    { "expr": "vuln_critical_per_workload", "legendFormat": "{{namespace}} / {{name}}" },
    { "expr": "vuln_high_per_workload", "legendFormat": "{{namespace}} / {{name}}" },
    { "expr": "vuln_medium_per_workload", "legendFormat": "{{namespace}} / {{name}}" },
    { "expr": "vuln_low_per_workload", "legendFormat": "{{namespace}} / {{name}}" },
    { "expr": "vuln_unknown_per_workload", "legendFormat": "{{namespace}} / {{name}}" }
   ]
  },
  {
   "title": "ConfigAudit Report Summary (Fixed)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 69 },
   "targets": [
    { "expr": "configaudit_critical_count" },
    { "expr": "configaudit_high_count" },
    { "expr": "configaudit_medium_count" },
    { "expr": "configaudit_low_count" }
   ]
  },
  { "title": "Misconfiguration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Severity Breakdown of all Misconfiguration",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_resource_configaudits{severity=\"Critical\"})",
     "legendFormat": "Critical"
    },
    {
     "expr": "sum(trivy_resource_configaudits{severity=\"High\"})",
     "legendFormat": "High"
    },
    {
     "expr": "sum(trivy_resource_configaudits{severity=\"Medium\"})",
     "legendFormat": "Medium"
    },
    {
     "expr": "sum(trivy_resource_configaudits{severity=\"Low\"})",
     "legendFormat": "Low"
    }
   ]
  },
  { "title": "RBAC Assessment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Severity Breakdown of RBAC Security Issues",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_role_rbacassessments{severity=\"Critical\"})",
     "legendFormat": "Critical"
    },
    {
     "expr": "sum(trivy_role_rbacassessments{severity=\"High\"})",
     "legendFormat": "High"
    },
    {
     "expr": "sum(trivy_role_rbacassessments{severity=\"Medium\"})",
     "legendFormat": "Medium"
    },
    {
     "expr": "sum(trivy_role_rbacassessments{severity=\"Low\"})",
     "legendFormat": "Low"
    },
    {
     "expr": "sum(trivy_role_rbacassessments{severity=\"UNKNOWN\"})",
     "legendFormat": "Unknown"
    }
   ]
  },
  { "title": "Exposed Secrets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Exposed Secrets per namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "sum(trivy_image_exposedsecrets) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CVE Severity Summary",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(critical_severity_cves)", "legendFormat": "Critical" },
    { "expr": "sum(high_severity_cves)", "legendFormat": "High" },
    { "expr": "sum(medium_severity_cves)", "legendFormat": "Medium" },
    { "expr": "sum(low_severity_cves)", "legendFormat": "Low" },
    { "expr": "sum(unknown_severity_cves)", "legendFormat": "Unknown" },
    { "expr": "sum(total_cves)", "legendFormat": "Total CVEs" }
   ]
  },
  {
   "title": "Number of Vulnerabilities by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}