apiVersion: v1
kind: Service
metadata:
  name: ai-prediction-exporter
  namespace: monitoring
  labels:
    app: ai-prediction-exporter
spec:
  selector:
    app: ai-prediction-exporter
  ports:
    - name: http
      port: 8001
      targetPort: 8001
